USE [CARWASH]
GO

/****** Object:  Table [dbo].[TIPOAUTO]    Script Date: 9/05/2019 06:09:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TIPOAUTO](
	[TIPOAUTO] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar](25) NULL,
 CONSTRAINT [PK_TIPOAUTO] PRIMARY KEY CLUSTERED 
(
	[TIPOAUTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

