USE [CARWASH]
GO

/****** Object:  Table [dbo].[SERVICIOS]    Script Date: 16/05/2019 01:40:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SERVICIOS](
	[CODPROD] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar](200) NULL,
	[IMPORTE] [float] NULL,
	[CODCATEGORIA] [int] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

