USE [CARWASH]
GO

/****** Object:  Table [dbo].[CLIENTES]    Script Date: 16/05/2019 01:39:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CLIENTES](
	[NOPLACA] [varchar](10) NOT NULL,
	[CODMARCA] [smallint] NULL,
	[COLOR] [varchar](20) NULL,
	[NOMCLIENTE] [varchar](100) NULL,
	[EMAIL] [varchar](50) NULL,
	[TELEFONO] [varchar](20) NULL,
	[DESCRIPCION] [varchar](100) NULL,
 CONSTRAINT [PK_CLIENTES] PRIMARY KEY CLUSTERED 
(
	[NOPLACA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

